# --------------------------------------------------------------
#
# Thanks for using BountyHunters!
#
# --------------------------------------------------------------

# Notifies players with the 'bountyhunters.update-notify' perm node when
# they join the server if a new update is available for download.
# Requires /reload when changed.
update-notify: true

# When enabled, some items that can't be picked up will
# drop from the target's body (can be any material).
# Looks cool with CHEST, GOLD_NUGGET, REDSTONE...
bounty-effect:
    enabled: true
    material: CHEST

# Time players have to wait to do /bounty twice.
# In seconds.
bounty-set-restriction: 120

# When toggled on, claiming a bounty or killing a
# player illegaly will not longer display a death message.
disable-death-message:
    auto-bounty: true
    bounty-claim: true

# Items that are dropped when claiming a bounty.
physical-rewards:
    enabled: false
    list:
        GOLD_NUGGET: 10
        REDSTONE: 2

# Commands sent by the console when a player claims a bounty.
#
# %target% returns the target's name and %player% the claimer's name.
# Commands support PlaceholderAPI placeholders.
#
# 'claim' corresponds to when a player claims a bounty normally.
# 'auto-bounty' corresponds to when a bounty is claimed illegaly.
#
# 'killer' are commands sent for the player who claimed the bounty.
# 'target' are commands sent for the bounty target.
bounty-commands:
    claim:
        killer: []
#       - '/give %killer% minecraft:diamond 10'
        target: []
#       - '/say %target% Someone claimed your bounty.'
    auto-bounty:
        killer: []
#       - '/jail %killer% 100'
        target: []
#       - '/say %target% You killed a man illegaly, watch out!'

# When enabled, it will automaticaly place a bounty onto any
# player who kills a player with no bounty on him (illegal kill).
auto-bounty:
    enabled: false
    reward: 100
    chance: 100

# Drops the player head when claming a bounty.
drop-head:
    enabled: false
    chance: 100

# Displays player skulls
# Can sometimes not work because of minecraft servers (too many requests).
display-player-skulls: true

# The tracking compass allows people to know where the people with a bounty on are.
# Required a /reload to take effect.
#
# The cooldown determines how often you can target a player in the menu (can fix spam from the hunter alert).
# The format corresponds to the number displayed on the compass name (see DecimalFormat (Java) on Google).
compass:
    enabled: true
    price: 1000
    target-cooldown: 240
    format: '0.#'

# Min and max bounty rewards.
# Set max to 0 to remove the max restriction.
min-reward: 0
max-reward: 0

# Tax taken when creating a bounty (to fight abuse).
# In % of the money reward. Must be between 0 and 100.
tax: 15

# Enables the display of death quotes when claiming a bounty.
display-death-quote-on-title: false
  
# Enables leveling rewards.
enable-quotes-levels-titles: true

# Worlds in which the bounty system is completely disabled.
world-blacklist:
- INSERT_WORLD_HERE

# You can claim the bounties you create. This also lets
# people target players using a bounty THEY created.
# Warning: can be abused.
own-bounty-claiming: true

# Displays particles around targeted players (requires /reload to take effect).
target-particles:
    enabled: true
    permission: ''

# Displayed formatted numbers (1,345B instead of 1,345,416,416).
formatted-numbers: true

# Enable/disable built-in plugin compatibility.
# Make sure you reload/restart your server afting changing any of these values.
plugin-compatibility:

    # Can only be enabled when Towny is installed.
    # When enabled, players within the same town can't claim each other's bounties.
    towny-bounty-friendly-fire: true
