# --------------------------------------------------------------
#
# Thanks for using BountyHunters!
#
# --------------------------------------------------------------

# Notifies players with the 'bountyhunters.update-notify' perm node when
# they join the server if a new update is available for download.
# Requires /reload when changed.
update-notify: true

# When enabled, some items that can't be picked up will
# drop from the target's body (can be any material).
# Looks cool with CHEST, GOLD_NUGGET, REDSTONE...
bounty-effect:
    enabled: true
    material: CHEST

# Time players have to wait to do /bounty twice.
# In seconds.
bounty-set-restriction: 120

# When toggled on, claiming a bounty or killing a
# player illegaly will not longer display a death message.
disable-death-message:
    auto-bounty: true
    bounty-claim: true

# Commands sent by the console when a player claims a bounty.
# %target% returns the target's name and %player% the claimer's
# name. Commands support PlaceholderAPI placeholders. 
# 'killer'/'target'/'creator' are the commands which
# placeholders are calculated using the corresponding players.
bounty-commands:

    # When a player claims a bounty.
    claim:
        killer: []
#       - '/give %killer% minecraft:diamond 10'
        target: []
#       - '/say %target% Someone claimed your bounty.'
        creator: []

    # When a player kills another player illegaly.
    auto-bounty:
        killer: []
#       - '/jail %killer% 100'
        target: []
#       - '/say %target% You killed a man illegaly, watch out!'
        creator: []

# When enabled, it will automaticaly place a bounty onto any
# player who kills a player with no bounty on him (illegal kill).
auto-bounty:
    enabled: false
    reward: 100
    chance: 100

# Displays a different login message when a player
# logs on with a bounty. Requires /reload when changed.
target-login-message:
    format: '&e%player% joined the game with a &6$%bounty%&e bounty!'
    enabled: true

# Drops the player head when claming a bounty.
drop-head:
    enabled: false
    chance: 100

# Displays player skulls
# Can sometimes not work because of minecraft servers (too many requests).
display-player-skulls: true

# Player tracking lets player use a tracking compass to hunt
# down their bounty target. On the one hand, it gives an
# advantage to the hunters because they can find the player, but
# it also lets the target know how many players are tracking him.
player-tracking:
    enabled: true
    
    # Permission needed to track a
    # player and to buy the compass.
    permission: ''
    
    # Also displays particles around the
    # target when holding the compass.
    target-particles: true
    
    # Price of the tracking compass.
    price: 1000
    
    # Cooldowns players need to wait before tracking a player.
    cooldown: 240

# Min and max bounty rewards.
# Set max to 0 to remove the max restriction.
min-reward: 0
max-reward: 0

# Tax taken when creating a bounty (to fight abuse).
# In % of the money reward. Must be between 0 and 100.
tax: 15

# Enables the display of death quotes when claiming a bounty.
display-death-quote-on-title: false
  
# Enables leveling rewards.
enable-quotes-levels-titles: true

# Worlds in which the bounty system is completely disabled.
world-blacklist:
- INSERT_WORLD_HERE

# You can claim the bounties you create. This also lets
# people target players using a bounty THEY created.
# Warning: can be abused.
own-bounty-claiming: true

# Displayed formatted numbers (1,345B instead of 1,345,416,416).
formatted-numbers: true

# Enable/disable built-in plugin compatibility.
# Make sure you reload/restart your server afting changing any of these values.
plugin-compatibility:

    # Can only be enabled when Towny is installed.
    # When enabled, players within the same town can't claim each other's bounties.
    towny-bounty-friendly-fire: true
